### ISSUE TITLE
Very odd bug.

### ISSUE THREAD

**Issue by Cluuey** [p3lim-wow/ExtraQuestButton#33]
I noticed this before reset but wasn't sure what was happening, after reset I noticed it again and took the time to get this screen shot and add the bug report.
The really odd part is that brighter area of grass, it moves as I move the camera around, it stops being bright after I hand the quest in. I tried capturing it but something has changed since I last recorded WoW and it isn't working now and given it's 3:20am now isn't the time to trouble shoot it!

![image](https://user-images.githubusercontent.com/10675078/97111840-1b150500-1735-11eb-8f5a-bbd1fad81630.png)

`/fstack` tells me it's _ExtraQuestButton.240d2708060_ and the artwork is _ExtraQuestButtonArtwork_, which is what we'd expect.
There's no reason for it to come up now, as you can see none of the quests have an icon next to them.
The quest I've just finished is [Crysa's Flyers](https://www.wowhead.com/quest=45083/crysas-flyers).

**Comment by p3lim** [comment]
It might be some funny stuff with the game renderer and that empty frame (which I've fixed, see #29), but I can't reproduce this myself.
I'm going to close this, but feel free to re-open if you encounter this again after the 90000.21-Release version coming out soon.

**Comment by bekaylai** [comment]
I think he's the same as me ? Most probably bugged after finished battle pet if I recall correctly

**Comment by p3lim** [comment]
@bekaylai He's pointing out this:
![image](https://user-images.githubusercontent.com/26496/97201585-e6e02980-17b2-11eb-92de-1e37460006ec.png)

**Comment by Cluuey** [comment]
According to the toc file I'm running `## Version: 90000.20-Release` and I'm still getting the empty button showing up.
I also noticed I'd get the camera icon pop up for a moment at the start of a pet battle even if I'm on the other continent. The camera icon comes from those silly quests where you take photos for a tourism brochure.

The highlighted texture is still there too but it doesn't clear instantly on handing the quest in, I'm guessing that's coincidental.

**Comment by p3lim** [comment]
> and I'm still getting the empty button showing up

I haven't released the version with the fix yet, need to solve #31 first.
